site_name: Homelab Portfolio
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - content.tabs.link
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Security: security.md
  - Automation: automation.md
  - Monitoring: monitoring.md
  - AI & LLM: ai-llm.md
  - Honeypots: honeypots.md
  - Forensics Lab: forensics-lab.md
  - Runbooks:
    - Backups & Restore: runbooks/backup-restore.md
  - Case Studies:
    - Shodan Enrichment: case-studies/shodan.md
